on:
  schedule:
    - cron: 0 0 * * *
  push:
    branchs:
      - main
  repository_dispatch:
    types:
      - site-build

name: Get OSM Data
jobs:
  Generate-POI-Data:
    name: Generate-POI-Data-Action
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@2.1.0
      with:
        fetch-depth: 2
    
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    
    - uses: actions/setup-java@v1
      with: 
        java-version: 11
        java-package: jre

    - name: instal gdal lib
      run: |
        apt update && apt install sudo
        sudo apt-get update && sudo apt-get install -y gdal-bin

    - name: fetch osmosis
      run: |
        wget https://github.com/openstreetmap/osmosis/releases/download/0.48.3/osmosis-0.48.3.tgz -O osmosis.tgz
        mkdir osmosis
        mv osmosis.tgz osmosis
        cd osmosis
        tar xzvf osmosis.tgz
        chmod a+x bin/osmosis
        cd ..

    - name: fetch osmconvert
      run: |
        wget http://m.m.i24.cc/osmconvert64 -O osmconvert
        chmod a+x osmconvert

    - name: download osm data
      run: wget https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
      #run: wget http://download.geofabrik.de/south-america/brazil/sul-latest.osm.pbf

    - name: extract osm data
      run: ./osmosis/bin/osmosis --read-pbf planet-latest.osm.pbf --tf accept-nodes aeroway=aerodrome,helipad amenity=bar,biergarden,cafe,fast_food,food_court,ice_crean,pub,restaurant,college,driving_school,kindergarten,language_school,library,toy_library,music_school,school,university,bicycle_parking,bicycle_repair_station,bicycle_rental,boat_rental,boat_sharing,bus_station,car_rental,car_wash,vehicle_inspection,charging_station,ferry_terminal,fuel,motorcycle_parking,parking,taxi,atm,bank,bureau_de_change,clinic,dentist,doctors,hospital,nursing_home,pharmacy,social_facility,veterinary,arts_centre,brothel,casino,cinema,community_centre,conference_centre,events_venue,fontain,gambling,love_hotel,nightclub,planetarium,public_bookcase,social_centre,stripclub,studio,swingerclub,theatre,courthouse,embassy,fire_station,police,post_box,post_depot,post_office,prision,ranger_station,townhall,bbq,shower,telephone,toilets,recycling,animal_boarding,animal_breeding,childcare,clock,crematorium,dive_centre,funeral_hall,grave_yard,internet_cafe,kitchen,marketplace,monastery,photo_booth,place_of_worship,public_bath,vending_machine building=dormitory,hotel,comercial,industrial,kiosk,office,retail,supermarket,wherehouse,cathedral,chapel,church,monastery,mosque,presbytery,religious,shrine,synagogue,temple,civic,fire_station,government,hospital,public,toilets,train_station,transportation,kindergarten,school,university,college,sports_hall,stadium,garage,garages,parking,military,bunker craft=atelier,bakery,blacksmith,boatbuilder,bookbuilder,brewery,builder,cabinet_maker,car_painter,carpenter,carpet_layer,clockmaker,confectionery,cooper,dental_technician,distilletery,door_construction,dressmaker,electronics_repair,embroiderer,electrician,engraver,floorer,gardener,glaziery,goldsmith,handcraft,hvac,insulation,interior_work,jeweller,joiner,key_cutter,locksmith,metal_construction,mint,musical_instrument,oil_mill,optician,organ_builder,painter,parquet_layer,paver,photographer,photographic_laboratory,piano_tuner,plasterer,plumber,pottery,printer,printmaker,roofer,saddler,sailmaker,sawmill,scaffolder,sculptor,shoemaker,signmaker,stand_builder,stonemason,stove_filter,sun_protection,tailor,tiler,tinsmith,toolmaker,turner,upholsterer,watchmaker,water_well_drilling,window_construction,winery emergency=ambulance_station,defibrillator historic=building,castle,church,city_get,fort,locomotive,memorial,monastery,ruins,tomb landuse=cemetery leisure=dance,dog_park,escape_game,fishing,fitness_centre,fitness_station,horse_riding,ice_rink,marina,miniature_golf,nature_reserve,park,pitch,playground,sports_centre,stadium,summer_camp,swimming_area,track,water_park man_made=lighthouse,obelisk,observatory,pier,telescope,windmill millitary=office office=accountant,advertising_agency,architect,association,charity,company,consulting,courier,coworking,diplomatic,educational_institution,employment_agency,energy_supplier,engineer,state_agent,finantial,finantial_advisor,forestry,foundation,government,guide,it,insurance,lawyer,logistics,moving_company,newspaper,ngo,notary,political_party,property_management,quango,religion,research,surveyor,tax_advisor,telecommunication,visa,water_utility public_transport=stop_position,platform,station,stop_area shop=* sport=* tourism=* --tf reject-ways  --tf reject-relations  --write-xml sul.nodes.osm

    - name: convert osm data
      run: |
        ./osmconvert planet.nodes.osm --drop-ways --drop-author --drop-relations --drop-versions > planet.poi.osm
        ogr2ogr -f GeoJSON pois.json planet.poi.osm points
        
    - name: upload json
      run: |        
        mkdir -p data        
        npm install
        node index.js
    #- name: Upload data artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: "data-folder"
    #    path: "sul.poi.json"